# Generated by Django 3.2.4 on 2021-07-12 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Productos', '0004_remove_producto_registrado_por'),
        ('Ventas', '0002_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 16, 23, 20, 122472)),
        ),
    ]
