# Generated by Django 3.2.4 on 2021-07-13 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_remove_producto_registrado_por'),
        ('Ventas', '0003_auto_20210712_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('importe', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Productos.producto')),
            ],
            options={
                'verbose_name': 'concepto',
                'verbose_name_plural': 'conceptos',
            },
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 21, 11, 19, 571906)),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='concepto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Ventas.venta'),
        ),
    ]
