# Generated by Django 3.2.4 on 2021-07-13 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20210712_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 15, 22, 11, 527723)),
        ),
    ]
