# Generated by Django 3.2.4 on 2021-07-14 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0015_alter_venta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='importe',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 14, 31, 27, 787479)),
        ),
    ]
